[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  map s <Plug>(easymotion-s2)
'''

[[plugins]]
repo = 'tpope/vim-commentary'

